/* TEST PAGE */

"use client";

import { useState } from "react";

export default function Image() {
  const [text, setText] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);

  const generateImage = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ text }),
      });
      const data = await response.json();
      setImageUrl(data.imageUrl);
    } catch (error) {
      console.error("Error generating image:", error);
    }
    setLoading(false);
  };

  return (
    <div style={{ textAlign: "center", padding: "20px" }}>
      <h1>Generate Image using DALL-E</h1>
      <input
        type="text"
        placeholder="Enter text to generate image"
        value={text}
        onChange={(e) => setText(e.target.value)}
        className="text-black"
        style={{ width: "300px", padding: "10px", margin: "10px" }}
      />
      <button onClick={generateImage} style={{ padding: "10px 20px" }}>
        Generate Image
      </button>
      {loading && <p>Loading...</p>}
      {imageUrl && (
        <div>
          <h2>Generated Image:</h2>
          <img
            src={imageUrl}
            alt="Generated by DALL-E"
            style={{ maxWidth: "100%" }}
          />
        </div>
      )}
    </div>
  );
}
